name: electroporation_modeling
channels:
  - conda-forge
  - defaults
dependencies:
  - ipywidgets=7.5.1
  - jupyterlab=2.1.5
  - nodejs
  - numpy
  - pandas
  - pip
  - python=3.8
  - scipy
  - seaborn
  - tqdm
  - ipykernel
  - arviz
  - pymc3
  - gspread
  - pip:
    - ipympl
# For gspread remember to add
# ~/.config/gspread/service_account.json
