name: electroporation_modeling
channels:
  - conda-forge
dependencies:
  - nb_black
  - scikit-learn-intelex
  - sympy
  - pymc3
  - watermark
  - nodejs
  - scipy
  - numpy
  - ipykernel
  - python
  - seaborn
  - pyjanitor
  - arviz
  - python-graphviz
  - tqdm
  - gspread
  - pip
  - pandas
  - theano-pymc
